### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by huangwch** [lmmarisej/Spring-Dynamic-Properties#1]
springValueProcessor.springValueRegistry.get(beanFactory, "VariableName"); 
---
这里的beanFactory，可以不用传入吗？直接使用默认的beanFactory不行吗？难道还会有多个beanFactory？

**Comment by lmmarisej** [comment]
> ## springValueProcessor.springValueRegistry.get(beanFactory, "VariableName");
> 这里的beanFactory，可以不用传入吗？直接使用默认的beanFactory不行吗？难道还会有多个beanFactory？

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/BeanFactory.html
不唯一
